/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlin_gson.app

import com.google.gson.Gson

data class User (
    val name: String = "",
    val age: Int = 0
)

data class Todo (
    val userId: Int,
    val id: Int,
    val title: String,
    val completed: Boolean
)

fun main() {

    println("JSON Object")

    val user = User(
        name = "Alfian",
        age = 20
    )
    println("user :")
    println(user)

    println("")

    println("userJson :")
    val userJson = Gson().toJson(user)
    println(userJson)
    println("Is userJson string ? ${userJson is String}")

    println("")

    val convertedUserJson = Gson().fromJson<User>(userJson, User::class.java)
    println("convertedUserJson :")
    println(convertedUserJson)

    println("")

    println("===============")
    println("JSON Array")

    val listUser = listOf(User("Andra", 20), User("Irvan", 19))
    println("listUser :")
    println(listUser)

    println("")

    val listUserJson = Gson().toJson(listUser)
    println("listUserJson :")
    println(listUserJson)

    println("")

    val convertedListUserJson = Gson().fromJson(listUserJson, Array<User>::class.java).toList()
    println("convertedListUserJson :")
    println(convertedListUserJson)

    println("")

    println("===============")
    println("JSON Object 2")

    val plainTodoJson = """
        {
          "userId": 1,
          "id": 1,
          "title": "delectus aut autem",
          "completed": false
        }
    """.trimIndent()
    val todo = Gson().fromJson(plainTodoJson, Todo::class.java)
    println("todo :")
    println(todo)
}
